---

- name: Check if selinux is installed
  command: getenforce
  register: command_result
  changed_when: False
  ignore_errors: True

- name: Install libselinux-python
  yum: name={{ item }}
  with_items: 
    - epel-release
    - libselinux-python
  when: command_result|success and command_result.stdout != 'Disabled'

